// RootLayout.tsx
import "./globals.css";
import StoreProvider from "../store/providers/StoreProvider";

export const metadata = {
  title: "Riot Games",
  description: "Generated by create next app",
  icons: "/imgs/riotgames/riot-games-icon.png",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StoreProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </StoreProvider>
  );
}
